### ISSUE TITLE
Workflow failing with “IndexError: list index out of range”

### ISSUE THREAD

**Issue by cassidyjames** [nanos/mastodon_get_replies#9]
It’s entirely possible I am doing something wrong, but I tried to follow the README instructions for setting this up. 😅

Log: 
```
2023-03-15T03:31:10.8031708Z Requested labels: ubuntu-latest
2023-03-15T03:31:10.8031750Z Job defined at: cassidyjames/mastodon_get_replies/.github/workflows/get_context.yml@refs/heads/main
2023-03-15T03:31:10.8031785Z Waiting for a runner to pick up this job...
2023-03-15T03:31:10.9608952Z Job is waiting for a hosted runner to come online.
2023-03-15T03:31:15.7317194Z Job is about to start running on the hosted runner: GitHub Actions 2 (hosted)
2023-03-15T03:31:20.7149283Z Current runner version: '2.302.1'
2023-03-15T03:31:20.7180556Z ##[group]Operating System
2023-03-15T03:31:20.7181174Z Ubuntu
2023-03-15T03:31:20.7181627Z 22.04.2
2023-03-15T03:31:20.7181947Z LTS
2023-03-15T03:31:20.7182310Z ##[endgroup]
2023-03-15T03:31:20.7182621Z ##[group]Runner Image
2023-03-15T03:31:20.7183910Z Image: ubuntu-22.04
2023-03-15T03:31:20.7184308Z Version: 20230305.1
2023-03-15T03:31:20.7184890Z Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20230305.1/images/linux/Ubuntu2204-Readme.md
2023-03-15T03:31:20.7185561Z Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230305.1
2023-03-15T03:31:20.7186085Z ##[endgroup]
2023-03-15T03:31:20.7186924Z ##[group]Runner Image Provisioner
2023-03-15T03:31:20.7187324Z 2.0.119.1
2023-03-15T03:31:20.7187608Z ##[endgroup]
2023-03-15T03:31:20.7188420Z ##[group]GITHUB_TOKEN Permissions
2023-03-15T03:31:20.7189138Z Contents: read
2023-03-15T03:31:20.7189505Z Metadata: read
2023-03-15T03:31:20.7190055Z Packages: read
2023-03-15T03:31:20.7190572Z ##[endgroup]
2023-03-15T03:31:20.7193565Z Secret source: Actions
2023-03-15T03:31:20.7194102Z Prepare workflow directory
2023-03-15T03:31:20.8210687Z Prepare all required actions
2023-03-15T03:31:20.8450399Z Getting action download info
2023-03-15T03:31:21.1364623Z Download action repository 'actions/setup-python@v4' (SHA:d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435)
2023-03-15T03:31:21.8307018Z Download action repository 'dawidd6/action-download-artifact@v2' (SHA:5e780fc7bbd0cac69fc73271ed86edf5dcb72d67)
2023-03-15T03:31:22.4156088Z Download action repository 'actions/upload-artifact@v3' (SHA:0b7f8abb1508181956e8e162db84b466c27e18ce)
2023-03-15T03:31:23.0276501Z Complete job name: run
2023-03-15T03:31:23.1399151Z ##[group]Run curl -s https://api.github.com/repos/nanos/mastodon_get_replies/releases/latest | jq .zipball_url | xargs wget -O download.zip
2023-03-15T03:31:23.1399934Z [36;1mcurl -s https://api.github.com/repos/nanos/mastodon_get_replies/releases/latest | jq .zipball_url | xargs wget -O download.zip[0m
2023-03-15T03:31:23.1400373Z [36;1munzip -j download.zip[0m
2023-03-15T03:31:23.1400642Z [36;1mmkdir artifacts[0m
2023-03-15T03:31:23.1400886Z [36;1mls -lR[0m
2023-03-15T03:31:23.1463891Z shell: /usr/bin/bash -e {0}
2023-03-15T03:31:23.1464203Z ##[endgroup]
2023-03-15T03:31:23.4598532Z --2023-03-15 03:31:23--  https://api.github.com/repos/nanos/mastodon_get_replies/zipball/v3.0.1
2023-03-15T03:31:23.4612388Z Resolving api.github.com (api.github.com)... 192.30.255.116
2023-03-15T03:31:23.4804263Z Connecting to api.github.com (api.github.com)|192.30.255.116|:443... connected.
2023-03-15T03:31:23.6476701Z HTTP request sent, awaiting response... 302 Found
2023-03-15T03:31:23.6477597Z Location: https://codeload.github.com/nanos/mastodon_get_replies/legacy.zip/refs/tags/v3.0.1 [following]
2023-03-15T03:31:23.6478550Z --2023-03-15 03:31:23--  https://codeload.github.com/nanos/mastodon_get_replies/legacy.zip/refs/tags/v3.0.1
2023-03-15T03:31:23.6508746Z Resolving codeload.github.com (codeload.github.com)... 192.30.255.120
2023-03-15T03:31:23.6697172Z Connecting to codeload.github.com (codeload.github.com)|192.30.255.120|:443... connected.
2023-03-15T03:31:23.8523167Z HTTP request sent, awaiting response... 200 OK
2023-03-15T03:31:23.8525178Z Length: 10876 (11K) [application/zip]
2023-03-15T03:31:23.8530014Z Saving to: ‘download.zip’
2023-03-15T03:31:23.8531375Z 
2023-03-15T03:31:23.8545945Z      0K ..........                                            100% 27.7M=0s
2023-03-15T03:31:23.8549115Z 
2023-03-15T03:31:23.8549827Z 2023-03-15 03:31:23 (27.7 MB/s) - ‘download.zip’ saved [10876/10876]
2023-03-15T03:31:23.8550102Z 
2023-03-15T03:31:23.8582667Z Archive:  download.zip
2023-03-15T03:31:23.8583897Z 248542d7a6767113a30085147b22551a81774546
2023-03-15T03:31:23.8591014Z   inflating: get_context.yml         
2023-03-15T03:31:23.8592278Z  extracting: .gitignore              
2023-03-15T03:31:23.8592590Z   inflating: LICENSE.md              
2023-03-15T03:31:23.8593727Z   inflating: README.md               
2023-03-15T03:31:23.8595522Z  extracting: blank                   
2023-03-15T03:31:23.8604326Z   inflating: get_context.py          
2023-03-15T03:31:23.8604670Z   inflating: requirements.txt        
2023-03-15T03:31:23.8635901Z .:
2023-03-15T03:31:23.8636227Z total 64
2023-03-15T03:31:23.8636990Z -rw-r--r-- 1 runner docker  1091 Mar 14 10:23 LICENSE.md
2023-03-15T03:31:23.8637530Z -rw-r--r-- 1 runner docker  5490 Mar 14 10:23 README.md
2023-03-15T03:31:23.8638004Z drwxr-xr-x 2 runner docker  4096 Mar 15 03:31 artifacts
2023-03-15T03:31:23.8638514Z -rw-r--r-- 1 runner docker     0 Mar 14 10:23 blank
2023-03-15T03:31:23.8639023Z -rw-r--r-- 1 runner docker 10876 Mar 15 03:31 download.zip
2023-03-15T03:31:23.8639621Z -rw-r--r-- 1 runner docker 24973 Mar 14 10:23 get_context.py
2023-03-15T03:31:23.8640103Z -rw-r--r-- 1 runner docker  1364 Mar 14 10:23 get_context.yml
2023-03-15T03:31:23.8640647Z -rw-r--r-- 1 runner docker   116 Mar 14 10:23 requirements.txt
2023-03-15T03:31:23.8640913Z 
2023-03-15T03:31:23.8641050Z ./artifacts:
2023-03-15T03:31:23.8641399Z total 0
2023-03-15T03:31:23.9023886Z ##[group]Run actions/setup-python@v4
2023-03-15T03:31:23.9024456Z with:
2023-03-15T03:31:23.9024796Z   python-version: 3.10
2023-03-15T03:31:23.9025088Z   cache: pip
2023-03-15T03:31:23.9025428Z   check-latest: false
2023-03-15T03:31:23.9026034Z   token: ***
2023-03-15T03:31:23.9026671Z   update-environment: true
2023-03-15T03:31:23.9027273Z ##[endgroup]
2023-03-15T03:31:24.3052528Z ##[group]Installed versions
2023-03-15T03:31:24.3193034Z Successfully set up CPython (3.10.10)
2023-03-15T03:31:24.3194333Z ##[endgroup]
2023-03-15T03:31:24.3945599Z [command]/opt/hostedtoolcache/Python/3.10.10/x64/bin/pip cache dir
2023-03-15T03:31:24.9136481Z /home/runner/.cache/pip
2023-03-15T03:31:25.1816491Z pip cache is not found
2023-03-15T03:31:25.2154450Z ##[group]Run pip install -r requirements.txt
2023-03-15T03:31:25.2154876Z [36;1mpip install -r requirements.txt[0m
2023-03-15T03:31:25.2215357Z shell: /usr/bin/bash -e {0}
2023-03-15T03:31:25.2215632Z env:
2023-03-15T03:31:25.2215946Z   pythonLocation: /opt/hostedtoolcache/Python/3.10.10/x64
2023-03-15T03:31:25.2216351Z   PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.10.10/x64/lib/pkgconfig
2023-03-15T03:31:25.2216740Z   Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.10/x64
2023-03-15T03:31:25.2217093Z   Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.10/x64
2023-03-15T03:31:25.2217454Z   Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.10/x64
2023-03-15T03:31:25.2217824Z   LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.10/x64/lib
2023-03-15T03:31:25.2219383Z ##[endgroup]
2023-03-15T03:31:26.1950731Z Collecting certifi==2022.12.7
2023-03-15T03:31:26.2949678Z   Downloading certifi-2022.12.7-py3-none-any.whl (155 kB)
2023-03-15T03:31:26.3499118Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.3/155.3 kB 2.9 MB/s eta 0:00:00
2023-03-15T03:31:26.5147440Z Collecting charset-normalizer==3.0.1
2023-03-15T03:31:26.5249831Z   Downloading charset_normalizer-3.0.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (198 kB)
2023-03-15T03:31:26.5388992Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 198.8/198.8 kB 18.1 MB/s eta 0:00:00
2023-03-15T03:31:26.6050751Z Collecting docutils==0.19
2023-03-15T03:31:26.6171138Z   Downloading docutils-0.19-py3-none-any.whl (570 kB)
2023-03-15T03:31:26.6339955Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 570.5/570.5 kB 42.2 MB/s eta 0:00:00
2023-03-15T03:31:26.6880780Z Collecting idna==3.4
2023-03-15T03:31:26.6930875Z   Downloading idna-3.4-py3-none-any.whl (61 kB)
2023-03-15T03:31:26.6995144Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 15.4 MB/s eta 0:00:00
2023-03-15T03:31:26.7766629Z Collecting requests==2.28.2
2023-03-15T03:31:26.7812699Z   Downloading requests-2.28.2-py3-none-any.whl (62 kB)
2023-03-15T03:31:26.7887157Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 14.3 MB/s eta 0:00:00
2023-03-15T03:31:26.8177366Z Collecting six==1.16.0
2023-03-15T03:31:26.8227023Z   Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
2023-03-15T03:31:26.8921064Z Collecting urllib3==1.26.14
2023-03-15T03:31:26.9029935Z   Downloading urllib3-1.26.14-py2.py3-none-any.whl (140 kB)
2023-03-15T03:31:26.9104852Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.6/140.6 kB 31.5 MB/s eta 0:00:00
2023-03-15T03:31:27.0687738Z Installing collected packages: charset-normalizer, urllib3, six, idna, docutils, certifi, requests
2023-03-15T03:31:27.8294022Z Successfully installed certifi-2022.12.7 charset-normalizer-3.0.1 docutils-0.19 idna-3.4 requests-2.28.2 six-1.16.0 urllib3-1.26.14
2023-03-15T03:31:28.2025134Z ##[group]Run dawidd6/action-download-artifact@v2
2023-03-15T03:31:28.2025470Z with:
2023-03-15T03:31:28.2025675Z   name: artifacts
2023-03-15T03:31:28.2025922Z   workflow: get_context.yml
2023-03-15T03:31:28.2026427Z   if_no_artifact_found: warn
2023-03-15T03:31:28.2026684Z   path: artifacts
2023-03-15T03:31:28.2027140Z   github_token: ***
2023-03-15T03:31:28.2027383Z   workflow_conclusion: success
2023-03-15T03:31:28.2027693Z   repo: cassidyjames/mastodon_get_replies
2023-03-15T03:31:28.2027977Z   check_artifacts: false
2023-03-15T03:31:28.2028232Z   search_artifacts: false
2023-03-15T03:31:28.2028466Z   skip_unpack: false
2023-03-15T03:31:28.2028713Z env:
2023-03-15T03:31:28.2029005Z   pythonLocation: /opt/hostedtoolcache/Python/3.10.10/x64
2023-03-15T03:31:28.2029394Z   PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.10.10/x64/lib/pkgconfig
2023-03-15T03:31:28.2029763Z   Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.10/x64
2023-03-15T03:31:28.2030154Z   Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.10/x64
2023-03-15T03:31:28.2030512Z   Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.10/x64
2023-03-15T03:31:28.2030862Z   LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.10/x64/lib
2023-03-15T03:31:28.2031157Z ##[endgroup]
2023-03-15T03:31:28.3654497Z ==> Repository: cassidyjames/mastodon_get_replies
2023-03-15T03:31:28.3661844Z ==> Artifact name: artifacts
2023-03-15T03:31:28.3662489Z ==> Local path: artifacts
2023-03-15T03:31:28.3663201Z ==> Workflow name: get_context.yml
2023-03-15T03:31:28.3663525Z ==> Workflow conclusion: success
2023-03-15T03:31:28.8778139Z ##[warning]no matching workflow run found with any artifacts?
2023-03-15T03:31:28.8823392Z ##[group]Run ls -lR
2023-03-15T03:31:28.8823701Z [36;1mls -lR[0m
2023-03-15T03:31:28.8886041Z shell: /usr/bin/bash -e {0}
2023-03-15T03:31:28.8886289Z env:
2023-03-15T03:31:28.8886596Z   pythonLocation: /opt/hostedtoolcache/Python/3.10.10/x64
2023-03-15T03:31:28.8887002Z   PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.10.10/x64/lib/pkgconfig
2023-03-15T03:31:28.8887394Z   Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.10/x64
2023-03-15T03:31:28.8887745Z   Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.10/x64
2023-03-15T03:31:28.8888114Z   Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.10/x64
2023-03-15T03:31:28.8888481Z   LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.10/x64/lib
2023-03-15T03:31:28.8888779Z ##[endgroup]
2023-03-15T03:31:28.8990268Z .:
2023-03-15T03:31:28.8990845Z total 64
2023-03-15T03:31:28.8991818Z -rw-r--r-- 1 runner docker  1091 Mar 14 10:23 LICENSE.md
2023-03-15T03:31:28.8992297Z -rw-r--r-- 1 runner docker  5490 Mar 14 10:23 README.md
2023-03-15T03:31:28.8992807Z drwxr-xr-x 2 runner docker  4096 Mar 15 03:31 artifacts
2023-03-15T03:31:28.8993268Z -rw-r--r-- 1 runner docker     0 Mar 14 10:23 blank
2023-03-15T03:31:28.8993707Z -rw-r--r-- 1 runner docker 10876 Mar 15 03:31 download.zip
2023-03-15T03:31:28.8994154Z -rw-r--r-- 1 runner docker 24973 Mar 14 10:23 get_context.py
2023-03-15T03:31:28.8994623Z -rw-r--r-- 1 runner docker  1364 Mar 14 10:23 get_context.yml
2023-03-15T03:31:28.8995069Z -rw-r--r-- 1 runner docker   116 Mar 14 10:23 requirements.txt
2023-03-15T03:31:28.8995289Z 
2023-03-15T03:31:28.8995388Z ./artifacts:
2023-03-15T03:31:28.8995614Z total 0
2023-03-15T03:31:28.9094923Z ##[group]Run python get_context.py *** mastodon.blaede.family 48 256 256 cassidy 256
2023-03-15T03:31:28.9095586Z [36;1mpython get_context.py *** mastodon.blaede.family 48 256 256 cassidy 256[0m
2023-03-15T03:31:28.9154983Z shell: /usr/bin/bash -e {0}
2023-03-15T03:31:28.9155236Z env:
2023-03-15T03:31:28.9155541Z   pythonLocation: /opt/hostedtoolcache/Python/3.10.10/x64
2023-03-15T03:31:28.9155923Z   PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.10.10/x64/lib/pkgconfig
2023-03-15T03:31:28.9156312Z   Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.10/x64
2023-03-15T03:31:28.9156671Z   Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.10/x64
2023-03-15T03:31:28.9157035Z   Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.10/x64
2023-03-15T03:31:28.9157400Z   LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.10/x64/lib
2023-03-15T03:31:28.9157682Z ##[endgroup]
2023-03-15T03:32:05.5047727Z Traceback (most recent call last):
2023-03-15T03:32:05.5048336Z Getting last 48 hrs of replies, and latest 256 posts in home timeline from mastodon.blaede.family
2023-03-15T03:32:05.5048718Z Found active user: cassidy
2023-03-15T03:32:05.5049088Z Found reply toot: https://mastodon.blaede.family/@cassidy/110024998531138529
2023-03-15T03:32:05.5049546Z Found reply toot: https://mastodon.blaede.family/@cassidy/110024963888568854
2023-03-15T03:32:05.5049977Z Found reply toot: https://mastodon.blaede.family/@cassidy/110024940118314942
2023-03-15T03:32:05.5050404Z Found reply toot: https://mastodon.blaede.family/@cassidy/110024931491621275
2023-03-15T03:32:05.5050813Z Found reply toot: https://mastodon.blaede.family/@cassidy/110024607291708389
2023-03-15T03:32:05.5051236Z Found reply toot: https://mastodon.blaede.family/@cassidy/110024102676236442
2023-03-15T03:32:05.5051666Z Found reply toot: https://mastodon.blaede.family/@cassidy/110023999736356730
2023-03-15T03:32:05.5052092Z Found reply toot: https://mastodon.blaede.family/@cassidy/110023835643309426
2023-03-15T03:32:05.5052518Z Found reply toot: https://mastodon.blaede.family/@cassidy/110023047132592424
2023-03-15T03:32:05.5052925Z Found reply toot: https://mastodon.blaede.family/@cassidy/110022804984013696
2023-03-15T03:32:05.5053363Z Found reply toot: https://mastodon.blaede.family/@cassidy/110022776859257298
2023-03-15T03:32:05.5053788Z Found reply toot: https://mastodon.blaede.family/@cassidy/110022758367052001
2023-03-15T03:32:05.5054204Z Found reply toot: https://mastodon.blaede.family/@cassidy/110022753304958284
2023-03-15T03:32:05.5054606Z Found reply toot: https://mastodon.blaede.family/@cassidy/110022750620366130
2023-03-15T03:32:05.5055024Z Found reply toot: https://mastodon.blaede.family/@cassidy/110022280550682771
2023-03-15T03:32:05.5055455Z Found reply toot: https://mastodon.blaede.family/@cassidy/110022228850343725
2023-03-15T03:32:05.5055879Z Found reply toot: https://mastodon.blaede.family/@cassidy/110022210962430763
2023-03-15T03:32:05.5056299Z Found reply toot: https://mastodon.blaede.family/@cassidy/110022173643432269
2023-03-15T03:32:05.5056712Z Found reply toot: https://mastodon.blaede.family/@cassidy/110022169488045032
2023-03-15T03:32:05.5057137Z Found reply toot: https://mastodon.blaede.family/@cassidy/110019697080949493
2023-03-15T03:32:05.5057563Z Found reply toot: https://mastodon.blaede.family/@cassidy/110017935213871779
2023-03-15T03:32:05.5057984Z Found reply toot: https://mastodon.blaede.family/@cassidy/110017501952428673
2023-03-15T03:32:05.5058390Z Found reply toot: https://mastodon.blaede.family/@cassidy/110017431196196315
2023-03-15T03:32:05.5058712Z Found 23 reply toots
2023-03-15T03:32:05.5059064Z Got context for toot https://mastodon.blaede.family/@cassidy/110024998531138529
2023-03-15T03:32:05.5059506Z Got context for toot https://mastodon.blaede.family/@cassidy/110024963888568854
2023-03-15T03:32:05.5059941Z Got context for toot https://mastodon.blaede.family/@cassidy/110024940118314942
2023-03-15T03:32:05.5060364Z Got context for toot https://mastodon.blaede.family/@cassidy/110024931491621275
2023-03-15T03:32:05.5061267Z Got context for toot https://mastodon.blaede.family/@cassidy/110024607291708389
2023-03-15T03:32:05.5061741Z Got context for toot https://mastodon.blaede.family/@cassidy/110024102676236442
2023-03-15T03:32:05.5062324Z Got context for toot https://mastodon.blaede.family/@cassidy/110023999736356730
2023-03-15T03:32:05.5075484Z   File "/home/runner/work/mastodon_get_replies/mastodon_get_replies/get_context.py", line 689, in <module>
2023-03-15T03:32:05.5076022Z Got context for toot https://mastodon.blaede.family/@cassidy/110023835643309426
2023-03-15T03:32:05.5076414Z     pull_context(
2023-03-15T03:32:05.5076927Z   File "/home/runner/work/mastodon_get_replies/mastodon_get_replies/get_context.py", line 40, in pull_context
2023-03-15T03:32:05.5077380Z     add_context_urls(server, access_token, context_urls, seen_urls)
2023-03-15T03:32:05.5077864Z   File "/home/runner/work/mastodon_get_replies/mastodon_get_replies/get_context.py", line 532, in add_context_urls
2023-03-15T03:32:05.5078251Z     for url in context_urls:
2023-03-15T03:32:05.5078675Z   File "/home/runner/work/mastodon_get_replies/mastodon_get_replies/get_context.py", line 492, in <genexpr>
2023-03-15T03:32:05.5079076Z     itertools.chain.from_iterable(
2023-03-15T03:32:05.5079507Z   File "/home/runner/work/mastodon_get_replies/mastodon_get_replies/get_context.py", line 355, in <genexpr>
2023-03-15T03:32:05.5079992Z     get_replied_toot_server_id(server, toot, replied_toot_server_ids, parsed_urls)
2023-03-15T03:32:05.5080914Z Got context for toot https://mastodon.blaede.family/@cassidy/110023047132592424
2023-03-15T03:32:05.5081484Z Got context for toot https://mastodon.blaede.family/@cassidy/110022804984013696
2023-03-15T03:32:05.5082020Z Got context for toot https://mastodon.blaede.family/@cassidy/110022776859257298
2023-03-15T03:32:05.5082559Z Got context for toot https://mastodon.blaede.family/@cassidy/110022758367052001
2023-03-15T03:32:05.5083084Z Got context for toot https://mastodon.blaede.family/@cassidy/110022753304958284
2023-03-15T03:32:05.5083596Z Got context for toot https://mastodon.blaede.family/@cassidy/110022750620366130
2023-03-15T03:32:05.5084123Z Got context for toot https://mastodon.blaede.family/@cassidy/110022280550682771
2023-03-15T03:32:05.5084676Z Got context for toot https://mastodon.blaede.family/@cassidy/110022228850343725
2023-03-15T03:32:05.5085192Z Got context for toot https://mastodon.blaede.family/@cassidy/110022210962430763
2023-03-15T03:32:05.5085710Z Got context for toot https://mastodon.blaede.family/@cassidy/110022173643432269
2023-03-15T03:32:05.5086232Z Got context for toot https://mastodon.blaede.family/@cassidy/110022169488045032
2023-03-15T03:32:05.5087565Z Got context for toot https://mastodon.blaede.family/@cassidy/110019697080949493
2023-03-15T03:32:05.5088014Z Got context for toot https://mastodon.blaede.family/@cassidy/110017935213871779
2023-03-15T03:32:05.5088444Z Got context for toot https://mastodon.blaede.family/@cassidy/110017501952428673
2023-03-15T03:32:05.5089004Z Got context for toot https://mastodon.blaede.family/@cassidy/110017431196196315
2023-03-15T03:32:05.5089351Z Found 31 known context toots
2023-03-15T03:32:05.5089754Z Discovered redirect for URL https://mastodon.blaede.family/@FineFindus@floss.social/110023703499781145
2023-03-15T03:32:05.5090222Z Got context for toot https://floss.social/@FineFindus/110023703499856524
2023-03-15T03:32:05.5090619Z Added context url https://floss.social/@sonny/110023814015856172
2023-03-15T03:32:05.5091098Z Discovered redirect for URL https://mastodon.blaede.family/@justinz@social.opendesktop.org/110024934764755193
2023-03-15T03:32:05.5091696Z Got context for toot https://social.opendesktop.org/@justinz/110024934654688230
2023-03-15T03:32:05.5092205Z Discovered redirect for URL https://mastodon.blaede.family/@justinz@social.opendesktop.org/110024644449119425
2023-03-15T03:32:05.5092687Z Got context for toot https://social.opendesktop.org/@justinz/110024644391728230
2023-03-15T03:32:05.5093445Z Discovered redirect for URL https://mastodon.blaede.family/@communiteatime@fosstodon.org/110024455190650671
2023-03-15T03:32:05.5093953Z Got context for toot https://fosstodon.org/@communiteatime/110024454995085213
2023-03-15T03:32:05.5094537Z Discovered redirect for URL https://mastodon.blaede.family/@vandys@goto.vsta.org/110024065409345789
2023-03-15T03:32:05.5095079Z Error getting context for toot https://goto.vsta.org/@vandys/statuses/01GVH4YDKFE9AFRZ6WRXS0QK5P. Status code: 401
2023-03-15T03:32:05.5095619Z Discovered redirect for URL https://mastodon.blaede.family/@Joseph_of_Earth@fosstodon.org/110023757816286497
2023-03-15T03:32:05.5096096Z Got context for toot https://fosstodon.org/@Joseph_of_Earth/110023757826966194
2023-03-15T03:32:05.5096569Z Discovered redirect for URL https://mastodon.blaede.family/@schlink@hachyderm.io/110023008179073203
2023-03-15T03:32:05.5097019Z Got context for toot https://hachyderm.io/@schlink/110023008163576219
2023-03-15T03:32:05.5097400Z Added context url https://hachyderm.io/@schlink/110023085200502690
2023-03-15T03:32:05.5097791Z Added context url https://hachyderm.io/@schlink/110023093857209669
2023-03-15T03:32:05.5098200Z Added context url https://octodon.social/@alienghic/110023013757536494
2023-03-15T03:32:05.5098599Z Added context url https://hachyderm.io/@schlink/110023018822456395
2023-03-15T03:32:05.5098993Z Added context url https://octodon.social/@alienghic/110023054065087700
2023-03-15T03:32:05.5099375Z Added context url https://hachyderm.io/@schlink/110023059265039386
2023-03-15T03:32:05.5099763Z Added context url https://octodon.social/@alienghic/110023062967678202
2023-03-15T03:32:05.5100172Z Added context url https://social.binarydad.com/@ryan/110023021042427958
2023-03-15T03:32:05.5100569Z Added context url https://floss.social/@downey/110023097070802026
2023-03-15T03:32:05.5100936Z Added context url https://hachyderm.io/@schlink/110023101998553219
2023-03-15T03:32:05.5102159Z Added context url https://floss.social/@downey/110023111380778319
2023-03-15T03:32:05.5102566Z Added context url https://mstdn.social/@MrBigEars/110024076748410502
2023-03-15T03:32:05.5102945Z Added context url https://vmst.io/@djwfyi/110024813738792924
2023-03-15T03:32:05.5103312Z Added context url https://fosstodon.org/@atoponce/110024853529562195
2023-03-15T03:32:05.5103708Z Added context url https://hachyderm.io/@schlink/110024854932015522
2023-03-15T03:32:05.5107489Z   File "/home/runner/work/mastodon_get_replies/mastodon_get_replies/get_context.py", line 369, in get_replied_toot_server_id
2023-03-15T03:32:05.5110865Z     mention = [
2023-03-15T03:32:05.5112463Z IndexError: list index out of range
2023-03-15T03:32:05.5400723Z ##[error]Process completed with exit code 1.
2023-03-15T03:32:05.5584291Z Cleaning up orphan processes
```

**Comment by nanos** [comment]
Hm. This is a bit of bad one, because it's from a part of the script that I haven't touched, and - to be honest - don't fully understand.

@abhin4v Are you by any chance able to set some light on this? Here is the context:

<img width="674" alt="image" src="https://user-images.githubusercontent.com/5182595/225236841-f582637c-952e-4543-94b1-9bfd625e24f4.png">

**Comment by nanos** [comment]
Amazing. Thanks @abhin4v!

@cassidyjames I'll update this shortly
